version: "3.9"

services:
  clion_remote_env:
    container_name: clion_remote_env
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.clion
    ports:
    - 127.0.0.1:2222:22
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    cap_add:
      - SYS_PTRACE