version: "3.9"

services:
  proc_image_processing:
    container_name: proc_image_processing
    restart: unless-stopped
    image: sonia-auv/proc_image_processing:cpu-latest
    build:
      context: .
      dockerfile: Dockerfile
    cap_add:
      - SYS_PTRACE

  clion_remote_env:
    container_name: clion_cpu_remote_env
    restart: unless-stopped
    image: sonia-auv/proc_image_processing:clion-cpu
    build:
      context: .
      dockerfile: Dockerfile.clion
      args:
        - MODE=cpu
    ports:
      - 127.0.0.1:2222:22
    cap_add:
      - SYS_PTRACE
    depends_on:
      - proc_image_processing