version: "3.9"

services:
  ros-master:
    container_name: ros-master
    image: ros:melodic-ros-core
    command: stdbuf -o L roscore

  ros-bridge:
    container_name: ros-bridge
    image: docker.pkg.github.com/sonia-auv/sonia-ros-bridge/sonia-ros-bridge:x86-perception-latest
    environment:
      - ROS_MASTER_URI=http://ros-master:11311
    depends_on:
      - ros-master

  octopus-telemetry:
    container_name: octopus-telemetry
    image: ghcr.io/sonia-auv/octopus-telemetry:latest
    ports:
      - 3000:3000
    environment:
      - ROS_MASTER_URI=ws://ros-master:9090
    depends_on:
      - ros-bridge

  proc_image_processing:
    container_name: proc_image_processing
    image: sonia-auv/proc_image_processing:local
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ROS_MASTER_URI=http://ros-master:11311
    depends_on:
      - ros-master
    volumes:
      - ./bags:/bags:ro

# docker-compose -f docker-compose-bags.yml up octopus-telemetry proc_image_processing
# docker exec -it proc_image_processing /bin/bash
# cd /bags
# rosbag play your.bag