ARG MODE="gpu"
FROM sonia-auv/proc_image_processing:${MODE}-latest
USER root
RUN apt update && apt install -y ssh gcc g++ gdb clang rsync tar libxmlrpcpp-dev librosconsole-dev librospack-dev
USER sonia