version: "3.9"

services:
  ros-master:
    container_name: ros-master
    image: ros:melodic-ros-core
    command: stdbuf -o L roscore
    network_mode: host

  ros-bridge:
    container_name: ros-bridge
    image: docker.pkg.github.com/sonia-auv/sonia-ros-bridge/sonia-ros-bridge:x86-perception-latest
    network_mode: host
    depends_on:
      - ros-master

  octopus-telemetry:
    container_name: octopus-telemetry
    image: ghcr.io/sonia-auv/octopus-telemetry:latest
    network_mode: host
    depends_on:
      - ros-bridge

  proc_image_processing:
    container_name: proc_image_processing
    image: sonia-auv/proc_image_processing:local
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    depends_on:
      - ros-master
    volumes:
      - ./bags:/bags:ro