name: dummy_filterchain
filters:
  - name: Rotate
    parameters:
      - name: enable
        value: 1
      - name: transpose
        value: 0
      - name: Rotation_type
        value: 1
  - name: ImageCropper
    parameters:
      - name: Enable
        value: 1
      - name: X Offset
        value: 381
      - name: Y Offset
        value: 60
      - name: X Reduction
        value: 400
      - name: Y Reduction
        value: 80