name: hsv_buoy_red
filters:
  - name: Rotate
    parameters:
      - name: enable
        value: 0
      - name: transpose
        value: 0
      - name: Rotation_type
        value: 0
  - name: HSVThreshold
    parameters:
      - name: enable
        value: 1
      - name: Hue Min
        value: 0
      - name: Hue Max
        value: 85
      - name: saturation Min
        value: 30
      - name: saturation Max
        value: 85
      - name: value Min
        value: 20
      - name: value Max
        value: 65
  - name: Erode
    parameters:
      - name: Enable
        value: 1
      - name: Square_kernel
        value: 1
      - name: Kernel_type
        value: 0
      - name: Width
        value: 5
      - name: Height
        value: 5
      - name: Iteration
        value: 1
  - name: Dilate
    parameters:
      - name: Enable
        value: 1
      - name: Square_kernel
        value: 1
      - name: Kernel_type
        value: 0
      - name: Width
        value: 5
      - name: Height
        value: 5
      - name: Iteration
        value: 1
  - name: ObjectFinder
    parameters:
      - name: Enable
        value: 1
      - name: Debug_contour
        value: 1
      - name: Use_convex_hull
        value: 0
      - name: Offset Y for fence
        value: 0
      - name: Offset Y for fence fraction
        value: 0.300000
      - name: 0. Check max y
        value: 1
      - name: 0. Maximum y coordinate
        value: 109.000000
      - name: "1. Min_area : red"
        value: 201.000000
      - name: "2. disable_ratio_check : blue"
        value: 0
      - name: 2. Ratio_target
        value: 1.000000
      - name: 2. Diff_from_ratio_target
        value: 0.100000
      - name: "3. Min_percent_filled : yellow"
        value: 50.000000
      - name: "4.1 Look_for_Rectangle : green"
        value: 0
      - name: "4.2 disable_angle_check : green"
        value: 0
      - name: 4.2 angle_target
        value: 0.000000
      - name: 4.2 Diff_from_angle_target
        value: 30.000000
      - name: 5. Eliminate_same_x
        value: 0
      - name: 5. Min_x_difference
        value: 50.000000
      - name: Vote_most_centered
        value: 1
      - name: Vote_most_upright
        value: 0
      - name: Vote_less_diff_from_target_ratio
        value: 0
      - name: Vote_length
        value: 0
      - name: Vote_higher
        value: 0
      - name: Vote most horizontal
        value: 1
      - name: ID
        value: buoy
      - name: spec1
        value: red
      - name: spec2
        value: blue
      - name: Contour_retreval
        value: 0