name: threshold_red
filters:
  - name: ImageCropper
    parameters:
      - name: Enable
        value: 1
      - name: X Offset
        value: 265
      - name: Y Offset
        value: 0
      - name: X Reduction
        value: 300
      - name: Y Reduction
        value: 0