name: middle_pipe
filters:
  - name: Blurr
    parameters:
      - name: Enable
        value: 0
      - name: Type
        value: 2
      - name: Kernel_size
        value: 1
  - name: InRange
    parameters:
      - name: Enable
        value: 0
      - name: HSVLowH
        value: 0
      - name: HSVHighH
        value: 255
      - name: HSVLowS
        value: 0
      - name: HSVHighS
        value: 255
      - name: HSVLowV
        value: 0
      - name: HSVHighV
        value: 255
      - name: LUVlowL
        value: 0
      - name: LUVhighL
        value: 255
      - name: LUVlowU
        value: 0
      - name: LUVhighU
        value: 255
      - name: LUVlowV
        value: 0
      - name: LUVhighV
        value: 255
  - name: Morphology
    parameters:
      - name: Enable
        value: 0
      - name: Morphology_type
        value: 0
      - name: Kernel_type
        value: 0
      - name: Iteration
        value: 1
      - name: Kernel_size
        value: 1
  - name: Morphology
    parameters:
      - name: Enable
        value: 0
      - name: Morphology_type
        value: 0
      - name: Kernel_type
        value: 0
      - name: Iteration
        value: 1
      - name: Kernel_size
        value: 1
  - name: ConvexHull
    parameters:
      - name: Enable
        value: 0
      - name: Mode
        value: 0
      - name: Method
        value: 0
  - name: ObjectFinder
    parameters:
      - name: Enable
        value: 0
      - name: Debug_contour
        value: 0
      - name: Look_for_Rectangle
        value: 0
      - name: disable_ratio_check
        value: 0
      - name: disable_angle_check
        value: 0
      - name: Use_convex_hull
        value: 0
      - name: Vote_most_centered
        value: 0
      - name: Vote_most_upright
        value: 0
      - name: Vote_less_diff_from_target_ratio
        value: 0
      - name: Vote_length
        value: 0
      - name: Vote_higher
        value: 0
      - name: ID
        value: buoy
      - name: spec1
        value: red
      - name: spec2
        value: blue
      - name: Min_area
        value: 200.000000
      - name: Ratio_target
        value: 0.500000
      - name: Diff_from_ratio_target
        value: 0.100000
      - name: angle_target
        value: 0.000000
      - name: Diff_from_angle_target
        value: 30.000000
      - name: Min_percent_filled
        value: 50.000000
      - name: Contour_retreval
        value: 0