name: simple_delorean_near_bache
filters:
  - name: Rotate
    parameters:
      - name: enable
        value: 0
      - name: Rotation_type
        value: 0
  - name: Dilate
    parameters:
      - name: Enable
        value: 0
      - name: Square_kernel
        value: 1
      - name: Kernel_type
        value: 0
      - name: Width
        value: 1
      - name: Height
        value: 1
      - name: Iteration
        value: 1
  - name: Morphology
    parameters:
      - name: Enable
        value: 0
      - name: Morphology_type
        value: 0
      - name: Kernel_type
        value: 0
      - name: Iteration
        value: 1
      - name: Kernel_size
        value: 1
  - name: SubtractAllPlanes
    parameters:
      - name: enable
        value: 0
      - name: Plane_1
        value: 1
      - name: Plane_2
        value: 1
      - name: Plane_3
        value: 1
      - name: Invert_plane_1
        value: 0
      - name: Invert_plane_2
        value: 0
      - name: Invert_plane_3
        value: 0
      - name: Weight_Plane_1
        value: 1.000000
      - name: Weight_Plane_2
        value: 1.000000
      - name: Weight_Plane_3
        value: 1.000000
  - name: Blurr
    parameters:
      - name: Enable
        value: 0
      - name: Type
        value: 2
      - name: Kernel_size
        value: 1
  - name: Sobel
    parameters:
      - name: Enable
        value: 0
      - name: Convert_to_uchar
        value: 1
      - name: use_pixel_intensity_correction
        value: 0
      - name: Delta
        value: 0.000000
      - name: Scale
        value: 1.000000
      - name: pixel_correction_power
        value: 1.000000
      - name: Size
        value: 2
  - name: ScharrAdding
    parameters:
      - name: Enable
        value: 0
      - name: Run_small_image
        value: 1
      - name: Convert_to_uchar
        value: 0
      - name: Delta
        value: 0.000000
      - name: Scale
        value: 1.000000
      - name: Mean_multiplier
        value: 1.000000
      - name: Blue
        value: 0
      - name: Green
        value: 0
      - name: Red
        value: 0
      - name: Hue
        value: 0
      - name: Saturation
        value: 0
      - name: Intensity
        value: 0
      - name: Gray
        value: 0
  - name: Morphology
    parameters:
      - name: Enable
        value: 0
      - name: Morphology_type
        value: 0
      - name: Kernel_type
        value: 0
      - name: Iteration
        value: 1
      - name: Kernel_size
        value: 1
  - name: StatsThreshold
    parameters:
      - name: Enable
        value: 0
      - name: Min_thresh
        value: 0
      - name: Mean_multiplier
        value: 1.000000
      - name: Standard_deviation_multiplier
        value: 1.000000
  - name: Threshold
    parameters:
      - name: Enable
        value: 0
      - name: Threshold_type
        value: 1
      - name: Max_value
        value: 100
  - name: Erode
    parameters:
      - name: Enable
        value: 0
      - name: Square_kernel
        value: 1
      - name: Kernel_type
        value: 0
      - name: Width
        value: 1
      - name: Height
        value: 1
      - name: Iteration
        value: 1
  - name: Dilate
    parameters:
      - name: Enable
        value: 0
      - name: Square_kernel
        value: 1
      - name: Kernel_type
        value: 0
      - name: Width
        value: 1
      - name: Height
        value: 1
      - name: Iteration
        value: 1
  - name: SubmarineFrameMasker
    parameters:
      - name: Enable
        value: 0
      - name: Rotation_type
        value: 0
  - name: DeloreanDetector
    parameters:
      - name: Enable
        value: 0
      - name: Debug_contour
        value: 0
      - name: Output_train
        value: 0
      - name: Min_area
        value: 200.000000
      - name: Ratio_target_big
        value: 0.500000
      - name: Ratio_target_small
        value: 0.500000
      - name: Diff_from_ratio_target
        value: 0.100000