name: simple_torpedoes_handle
filters:
  - name: SubtractAllPlanes
    parameters:
      - name: enable
        value: 0
      - name: Plane_1
        value: 1
      - name: Plane_2
        value: 1
      - name: Plane_3
        value: 1
      - name: Invert_plane_1
        value: 0
      - name: Invert_plane_2
        value: 0
      - name: Invert_plane_3
        value: 0
      - name: Weight_Plane_1
        value: 1.000000
      - name: Weight_Plane_2
        value: 1.000000
      - name: Weight_Plane_3
        value: 1.000000
  - name: WhiteNoiseTakedown
    parameters:
      - name: Enable
        value: 0
      - name: LowB
        value: 0
      - name: HighB
        value: 0
      - name: LowG
        value: 0
      - name: HighG
        value: 0
      - name: LowR
        value: 0
      - name: HighR
        value: 0
      - name: Channel_view
        value: 0
  - name: Threshold
    parameters:
      - name: Enable
        value: 0
      - name: Threshold_type
        value: 1
      - name: Max_value
        value: 100
  - name: Morphology
    parameters:
      - name: Enable
        value: 0
      - name: Morphology_type
        value: 0
      - name: Kernel_type
        value: 0
      - name: Iteration
        value: 1
      - name: Kernel_size
        value: 1
  - name: Erode
    parameters:
      - name: Enable
        value: 0
      - name: Square_kernel
        value: 1
      - name: Kernel_type
        value: 0
      - name: Width
        value: 1
      - name: Height
        value: 1
      - name: Iteration
        value: 1
  - name: Dilate
    parameters:
      - name: Enable
        value: 0
      - name: Square_kernel
        value: 1
      - name: Kernel_type
        value: 0
      - name: Width
        value: 1
      - name: Height
        value: 1
      - name: Iteration
        value: 1
  - name: ObjectFinder
    parameters:
      - name: Enable
        value: 0
      - name: Debug_contour
        value: 0
      - name: Look_for_Rectangle
        value: 0
      - name: disable_ratio_check
        value: 0
      - name: disable_angle_check
        value: 0
      - name: Use_convex_hull
        value: 0
      - name: Vote_most_centered
        value: 0
      - name: Vote_most_upright
        value: 0
      - name: Vote_less_diff_from_target_ratio
        value: 0
      - name: Vote_length
        value: 0
      - name: Vote_higher
        value: 0
      - name: ID
        value: buoy
      - name: spec1
        value: red
      - name: spec2
        value: blue
      - name: Min_area
        value: 200.000000
      - name: Ratio_target
        value: 0.500000
      - name: Diff_from_ratio_target
        value: 0.100000
      - name: angle_target
        value: 0.000000
      - name: Diff_from_angle_target
        value: 30.000000
      - name: Min_percent_filled
        value: 50.000000
      - name: Contour_retreval
        value: 0