name: deep_front
filters:
  - name: Deep2019
    parameters:
      - name: Enable
        value: 0
      - name: Debug contour
        value: 1
      - name: vetalas
        value: 0
      - name: draugr
        value: 0
      - name: jiangshi
        value: 1
      - name: answag
        value: 0
      - name: vampire
        value: 0
      - name: bat
        value: 0
      - name: wolf
        value: 0
  - name: SubtractAllPlanes
    parameters:
      - name: enable
        value: 1
      - name: Plane_1
        value: 5
      - name: Plane_2
        value: 4
      - name: Plane_3
        value: 0
      - name: Invert_plane_1
        value: 0
      - name: Invert_plane_2
        value: 0
      - name: Invert_plane_3
        value: 0
      - name: Weight_Plane_1
        value: 1.000000
      - name: Weight_Plane_2
        value: 1.000000
      - name: Weight_Plane_3
        value: 1.000000
  - name: Threshold
    parameters:
      - name: Enable
        value: 1
      - name: Threshold_type
        value: 0
      - name: Max_value
        value: 196
  - name: Dilate
    parameters:
      - name: Enable
        value: 1
      - name: Square_kernel
        value: 1
      - name: Kernel_type
        value: 0
      - name: Width
        value: 3
      - name: Height
        value: 3
      - name: Iteration
        value: 2
  - name: Erode
    parameters:
      - name: Enable
        value: 1
      - name: Square_kernel
        value: 1
      - name: Kernel_type
        value: 0
      - name: Width
        value: 5
      - name: Height
        value: 5
      - name: Iteration
        value: 2
  - name: Blurr
    parameters:
      - name: Enable
        value: 1
      - name: Type
        value: 2
      - name: Kernel_size
        value: 3
  - name: Threshold
    parameters:
      - name: Enable
        value: 1
      - name: Threshold_type
        value: 0
      - name: Max_value
        value: 100
  - name: VampireTorpidoesDetectorClose
    parameters:
      - name: Enable
        value: 1
      - name: Debug_contour
        value: 1
      - name: Look_for_Ellipse
        value: 0
      - name: Look_for_Heart
        value: 0
      - name: Min_area
        value: 5000.000000
      - name: Max_area
        value: 999999.000000