name: deep_front
filters:
  - name: Deep2019Filter
    parameters:
      - name: Enable
        value: 0
      - name: Debug contour
        value: 1
      - name: Vetalas
        value: 0
      - name: Draugr
        value: 0
      - name: Jiangshi
        value: 1
      - name: Answag
        value: 0
      - name: Vampire
        value: 0
      - name: Bat
        value: 0
      - name: Wolf
        value: 0
  - name: SubtractAllPlanesFilter
    parameters:
      - name: Enable
        value: 1
      - name: Plane_1
        value: 5
      - name: Plane_2
        value: 2
      - name: Plane_3
        value: 0
      - name: Invert_plane_1
        value: 0
      - name: Invert_plane_2
        value: 0
      - name: Invert_plane_3
        value: 0
      - name: Weight_Plane_1
        value: 1.000000
      - name: Weight_Plane_2
        value: 1.000000
      - name: Weight_Plane_3
        value: 1.000000
  - name: ThresholdFilter
    parameters:
      - name: Enable
        value: 1
      - name: Threshold_type
        value: 0
      - name: Max_value
        value: 150
  - name: ErodeFilter
    parameters:
      - name: Enable
        value: 1
      - name: Square_kernel
        value: 1
      - name: Kernel_type
        value: 0
      - name: Width
        value: 2
      - name: Height
        value: 2
      - name: Iteration
        value: 1
  - name: DilateFilter
    parameters:
      - name: Enable
        value: 1
      - name: Square_kernel
        value: 1
      - name: Kernel_type
        value: 0
      - name: Width
        value: 3
      - name: Height
        value: 3
      - name: Iteration
        value: 5
  - name: BlurFilter
    parameters:
      - name: Enable
        value: 1
      - name: Type
        value: 2
      - name: Kernel_size
        value: 3
  - name: ThresholdFilter
    parameters:
      - name: Enable
        value: 1
      - name: Threshold_type
        value: 0
      - name: Max_value
        value: 100
  - name: VampireTorpedoesCloseDetector
    parameters:
      - name: Enable
        value: 1
      - name: Debug_contour
        value: 1
      - name: Look_for_Ellipse
        value: 1
      - name: Look_for_Heart
        value: 0
      - name: Min_area
        value: 2000.000000
      - name: Max_area
        value: 1000000.000000