name: deep_front
filters:
  - name: Deep2019Filter
    parameters:
      - name: Enable
        value: 0
      - name: Debug contour
        value: 1
      - name: Vetalas
        value: 0
      - name: Draugr
        value: 0
      - name: Jiangshi
        value: 1
      - name: Answag
        value: 0
      - name: Vampire
        value: 0
      - name: Bat
        value: 0
      - name: Wolf
        value: 0
  - name: SubtractAllPlanesFilter
    parameters:
      - name: Enable
        value: 1
      - name: Plane 1
        value: 5
      - name: Plane 2
        value: 2
      - name: Plane 3
        value: 0
      - name: Invert plane 1
        value: 0
      - name: Invert plane 2
        value: 0
      - name: Invert plane 3
        value: 0
      - name: Weight plane 1
        value: 1.000000
      - name: Weight plane 2
        value: 1.000000
      - name: Weight plane 3
        value: 1.000000
  - name: ThresholdFilter
    parameters:
      - name: Enable
        value: 1
      - name: Threshold type
        value: 0
      - name: Maximum value
        value: 150
  - name: ErodeFilter
    parameters:
      - name: Enable
        value: 1
      - name: Square kernel
        value: 1
      - name: Kernel type
        value: 0
      - name: Width
        value: 2
      - name: Height
        value: 2
      - name: Iteration
        value: 1
  - name: DilateFilter
    parameters:
      - name: Enable
        value: 1
      - name: Square kernel
        value: 1
      - name: Kernel type
        value: 0
      - name: Width
        value: 3
      - name: Height
        value: 3
      - name: Iteration
        value: 5
  - name: BlurFilter
    parameters:
      - name: Enable
        value: 1
      - name: Type
        value: 2
      - name: Kernel size
        value: 3
  - name: ThresholdFilter
    parameters:
      - name: Enable
        value: 1
      - name: Threshold type
        value: 0
      - name: Maximum value
        value: 100
  - name: VampireTorpedoesCloseDetector
    parameters:
      - name: Enable
        value: 1
      - name: Debug contour
        value: 1
      - name: Look for ellipse
        value: 1
      - name: Look_for_Heart
        value: 0
      - name: Minimum area
        value: 2000.000000
      - name: Maximum area
        value: 1000000.000000