name: simple_body_baby
filters:
  - name: CropFilter
    parameters:
      - name: Enable
        value: 0
      - name: X Offset
        value: 200
      - name: Y Offset
        value: 150
      - name: X Reduction
        value: 200
      - name: Y Reduction
        value: 0
  - name: SubtractAllPlanesFilter
    parameters:
      - name: Enable
        value: 1
      - name: Plane 1
        value: 6
      - name: Plane 2
        value: 4
      - name: Plane 3
        value: 0
      - name: Invert plane 1
        value: 0
      - name: Invert plane 2
        value: 0
      - name: Invert plane 3
        value: 0
      - name: Weight plane 1
        value: 1.000000
      - name: Weight plane 2
        value: 1.000000
      - name: Weight plane 3
        value: 1.000000
  - name: ThresholdFilter
    parameters:
      - name: Enable
        value: 1
      - name: Threshold type
        value: 1
      - name: Maximum value
        value: 20
  - name: ErodeFilter
    parameters:
      - name: Enable
        value: 1
      - name: Square kernel
        value: 1
      - name: Kernel type
        value: 0
      - name: Width
        value: 2
      - name: Height
        value: 2
      - name: Iteration
        value: 3
  - name: DilateFilter
    parameters:
      - name: Enable
        value: 1
      - name: Square kernel
        value: 1
      - name: Kernel type
        value: 0
      - name: Width
        value: 1
      - name: Height
        value: 1
      - name: Iteration
        value: 1
  - name: BlurFilter
    parameters:
      - name: Enable
        value: 1
      - name: Type
        value: 3
      - name: Kernel size
        value: 10
  - name: VampireBodyDetector
    parameters:
      - name: Enable
        value: 1
      - name: Debug contour
        value: 1
      - name: Look for rectangle
        value: 1
      - name: Minimum area
        value: 4000.000000
      - name: Maximum area
        value: 10000.000000