name: simple_body_baby
filters:
  - name: ImageCropper
    parameters:
      - name: Enable
        value: 1
      - name: X Offset
        value: 200
      - name: Y Offset
        value: 150
      - name: X Reduction
        value: 200
      - name: Y Reduction
        value: 0
  - name: SubtractAllPlanes
    parameters:
      - name: enable
        value: 1
      - name: Plane_1
        value: 3
      - name: Plane_2
        value: 2
      - name: Plane_3
        value: 0
      - name: Invert_plane_1
        value: 0
      - name: Invert_plane_2
        value: 0
      - name: Invert_plane_3
        value: 0
      - name: Weight_Plane_1
        value: 1.000000
      - name: Weight_Plane_2
        value: 1.000000
      - name: Weight_Plane_3
        value: 1.000000
  - name: Threshold
    parameters:
      - name: Enable
        value: 1
      - name: Threshold_type
        value: 0
      - name: Max_value
        value: 9
  - name: Blurr
    parameters:
      - name: Enable
        value: 0
      - name: Type
        value: 3
      - name: Kernel_size
        value: 9
  - name: VampireBodyDetector
    parameters:
      - name: Enable
        value: 1
      - name: Debug_contour
        value: 1
      - name: Look_for_Rectangle
        value: 1
      - name: Min_area
        value: 1.000000
      - name: Max_area
        value: 50000.000000
  - name: Canny
    parameters:
      - name: Enable
        value: 1
      - name: l2_gradient
        value: 0
      - name: thres_one
        value: 100
      - name: thres_two
        value: 200
      - name: Aperture_size
        value: 3