name: simple_vampire
filters:
  - name: ImageCropper
    parameters:
      - name: Enable
        value: 0
      - name: X Offset
        value: 0
      - name: Y Offset
        value: 0
      - name: X Reduction
        value: 0
      - name: Y Reduction
        value: 0
  - name: SubtractAllPlanes
    parameters:
      - name: enable
        value: 1
      - name: Plane_1
        value: 2
      - name: Plane_2
        value: 1
      - name: Plane_3
        value: 0
      - name: Invert_plane_1
        value: 0
      - name: Invert_plane_2
        value: 0
      - name: Invert_plane_3
        value: 0
      - name: Weight_Plane_1
        value: 1.000000
      - name: Weight_Plane_2
        value: 1.000000
      - name: Weight_Plane_3
        value: 1.000000
  - name: Threshold
    parameters:
      - name: Enable
        value: 1
      - name: Threshold_type
        value: 0
      - name: Max_value
        value: 9
  - name: Dilate
    parameters:
      - name: Enable
        value: 1
      - name: Square_kernel
        value: 1
      - name: Kernel_type
        value: 0
      - name: Width
        value: 2
      - name: Height
        value: 2
      - name: Iteration
        value: 2
  - name: Erode
    parameters:
      - name: Enable
        value: 1
      - name: Square_kernel
        value: 1
      - name: Kernel_type
        value: 0
      - name: Width
        value: 3
      - name: Height
        value: 3
      - name: Iteration
        value: 2
  - name: AdaptiveThreshold
    parameters:
      - name: Enable
        value: 1
      - name: Method
        value: 1
      - name: Threshold_type
        value: 0
      - name: Size
        value: 40
      - name: C_param
        value: 0.000000
  - name: RemoveMask
    parameters:
      - name: Enable
        value: 0
      - name: Type
        value: 2
      - name: Kernel_size
        value: 1
  - name: TorpedoesDetector
    parameters:
      - name: Enable
        value: 1
      - name: Debug_contour
        value: 1
      - name: Sensibility
        value: 0.050000
      - name: Minimum Area
        value: 150.000000
      - name: Angle
        value: 0.750000
      - name: Median multp.
        value: 2.000000
      - name: PCA Ratio max
        value: 2.500000
      - name: PCA Ratio min
        value: 1.000000