name: simple_pipe
filters:
  - name: Rotate
    parameters:
      - name: enable
        value: 1
      - name: transpose
        value: 0
      - name: Rotation_type
        value: 3
  - name: SubtractAllPlanes
    parameters:
      - name: enable
        value: 1
      - name: Plane_1
        value: 3
      - name: Plane_2
        value: 2
      - name: Plane_3
        value: 0
      - name: Invert_plane_1
        value: 0
      - name: Invert_plane_2
        value: 0
      - name: Invert_plane_3
        value: 0
      - name: Weight_Plane_1
        value: 1.000000
      - name: Weight_Plane_2
        value: 1.000000
      - name: Weight_Plane_3
        value: 1.000000
  - name: Blurr
    parameters:
      - name: Enable
        value: 0
      - name: Type
        value: 2
      - name: Kernel_size
        value: 1
  - name: StatsThreshold
    parameters:
      - name: Enable
        value: 0
      - name: Min_thresh
        value: 0
      - name: Mean_multiplier
        value: 1.000000
      - name: Standard_deviation_multiplier
        value: 1.000000
  - name: Threshold
    parameters:
      - name: Enable
        value: 1
      - name: Threshold_type
        value: 0
      - name: Max_value
        value: 59
  - name: Erode
    parameters:
      - name: Enable
        value: 0
      - name: Square_kernel
        value: 1
      - name: Kernel_type
        value: 0
      - name: Width
        value: 1
      - name: Height
        value: 1
      - name: Iteration
        value: 1
  - name: Dilate
    parameters:
      - name: Enable
        value: 1
      - name: Square_kernel
        value: 1
      - name: Kernel_type
        value: 0
      - name: Width
        value: 2
      - name: Height
        value: 1
      - name: Iteration
        value: 1
  - name: PipeDetector
    parameters:
      - name: Enable
        value: 1
      - name: Debug_contour
        value: 1
      - name: Look_for_Rectangle
        value: 0
      - name: Min_area
        value: 400.000000