name: simple_body_baby
filters:
  - name: CropFilter
    parameters:
      - name: Enable
        value: 0
      - name: X Offset
        value: 200
      - name: Y Offset
        value: 150
      - name: X Reduction
        value: 200
      - name: Y Reduction
        value: 0
  - name: SubtractAllPlanesFilter
    parameters:
      - name: enable
        value: 1
      - name: Plane_1
        value: 6
      - name: Plane_2
        value: 4
      - name: Plane_3
        value: 0
      - name: Invert_plane_1
        value: 0
      - name: Invert_plane_2
        value: 0
      - name: Invert_plane_3
        value: 0
      - name: Weight_Plane_1
        value: 1.000000
      - name: Weight_Plane_2
        value: 1.000000
      - name: Weight_Plane_3
        value: 1.000000
  - name: ThresholdFilter
    parameters:
      - name: Enable
        value: 1
      - name: Threshold_type
        value: 1
      - name: Max_value
        value: 20
  - name: ErodeFilter
    parameters:
      - name: Enable
        value: 1
      - name: Square_kernel
        value: 1
      - name: Kernel_type
        value: 0
      - name: Width
        value: 2
      - name: Height
        value: 2
      - name: Iteration
        value: 3
  - name: DilateFilter
    parameters:
      - name: Enable
        value: 1
      - name: Square_kernel
        value: 1
      - name: Kernel_type
        value: 0
      - name: Width
        value: 1
      - name: Height
        value: 1
      - name: Iteration
        value: 1
  - name: BlurFilter
    parameters:
      - name: Enable
        value: 1
      - name: Type
        value: 3
      - name: Kernel_size
        value: 10
  - name: VampireBodyDetector
    parameters:
      - name: Enable
        value: 1
      - name: Debug_contour
        value: 1
      - name: Look_for_Rectangle
        value: 1
      - name: Min_area
        value: 4000.000000
      - name: Max_area
        value: 10000.000000