name: simple_fence
filters:
  - name: Rotate
    parameters:
      - name: enable
        value: 0
      - name: transpose
        value: 0
      - name: Rotation_type
        value: 3
  - name: ContrastBrightness
    parameters:
      - name: enable
        value: 1
      - name: Contrast
        value: 4.000000
      - name: Brightness
        value: -100.000000
  - name: ContrastBrightness
    parameters:
      - name: enable
        value: 1
      - name: Contrast
        value: 1.000000
      - name: Brightness
        value: -15.000000
  - name: Blurr
    parameters:
      - name: Enable
        value: 1
      - name: Type
        value: 2
      - name: Kernel_size
        value: 3
  - name: ImageAccumulator
    parameters:
      - name: Enable
        value: 0
      - name: NB_of_images
        value: 2
      - name: Method_to_use
        value: 0
  - name: SubtractAllPlanes
    parameters:
      - name: enable
        value: 1
      - name: Plane_1
        value: 2
      - name: Plane_2
        value: 1
      - name: Plane_3
        value: 0
      - name: Invert_plane_1
        value: 0
      - name: Invert_plane_2
        value: 0
      - name: Invert_plane_3
        value: 0
      - name: Weight_Plane_1
        value: 2.100000
      - name: Weight_Plane_2
        value: 2.200000
      - name: Weight_Plane_3
        value: 2.000000
  - name: Threshold
    parameters:
      - name: Enable
        value: 1
      - name: Threshold_type
        value: 0
      - name: Max_value
        value: 55
  - name: RemoveMask
    parameters:
      - name: Enable
        value: 0
      - name: Type
        value: 2
      - name: Kernel_size
        value: 1
  - name: SubtractAllPlanes
    parameters:
      - name: enable
        value: 0
      - name: Plane_1
        value: 3
      - name: Plane_2
        value: 1
      - name: Plane_3
        value: 0
      - name: Invert_plane_1
        value: 1
      - name: Invert_plane_2
        value: 0
      - name: Invert_plane_3
        value: 0
      - name: Weight_Plane_1
        value: 1.000000
      - name: Weight_Plane_2
        value: 3.100000
      - name: Weight_Plane_3
        value: 1.000000
  - name: Threshold
    parameters:
      - name: Enable
        value: 0
      - name: Threshold_type
        value: 0
      - name: Max_value
        value: 6
  - name: Dilate
    parameters:
      - name: Enable
        value: 1
      - name: Square_kernel
        value: 0
      - name: Kernel_type
        value: 2
      - name: Width
        value: 5
      - name: Height
        value: 9
      - name: Iteration
        value: 2
  - name: Morphology
    parameters:
      - name: Enable
        value: 1
      - name: Morphology_type
        value: 3
      - name: Kernel_type
        value: 0
      - name: Iteration
        value: 1
      - name: Kernel_size
        value: 3
  - name: Morphology
    parameters:
      - name: Enable
        value: 1
      - name: Morphology_type
        value: 4
      - name: Kernel_type
        value: 0
      - name: Iteration
        value: 2
      - name: Kernel_size
        value: 7
  - name: Erode
    parameters:
      - name: Enable
        value: 0
      - name: Square_kernel
        value: 1
      - name: Kernel_type
        value: 2
      - name: Width
        value: 1
      - name: Height
        value: 5
      - name: Iteration
        value: 1
  - name: ObjectFinder
    parameters:
      - name: Enable
        value: 1
      - name: Debug_contour
        value: 1
      - name: Use_convex_hull
        value: 1
      - name: Offset Y for fence
        value: 1
      - name: Offset Y for fence fraction
        value: 0.300000
      - name: 0. Check max y
        value: 0
      - name: 0. Maximum y coordinate
        value: 95.000000
      - name: "1. Min_area : red"
        value: 100.000000
      - name: "2. disable_ratio_check : blue"
        value: 0
      - name: 2. Ratio_target
        value: 0.200000
      - name: 2. Diff_from_ratio_target
        value: 0.300000
      - name: "3. Min_percent_filled : yellow"
        value: 6.000000
      - name: "4.1 Look_for_Rectangle : green"
        value: 0
      - name: "4.2 disable_angle_check : green"
        value: 0
      - name: 4.2 angle_target
        value: 90.000000
      - name: 4.2 Diff_from_angle_target
        value: 20.000000
      - name: 5. Eliminate_same_x
        value: 0
      - name: 5. Min_x_difference
        value: 50.000000
      - name: Vote_most_centered
        value: 1
      - name: Vote_most_upright
        value: 0
      - name: Vote_less_diff_from_target_ratio
        value: 1
      - name: Vote_length
        value: 1
      - name: Vote_higher
        value: 1
      - name: Vote most horizontal
        value: 1
      - name: ID
        value: fence
      - name: spec1
        value: yellow
      - name: spec2
        value: yellow
      - name: Contour_retreval
        value: 0