name: simple_dice2
filters:
  - name: Rotate
    parameters:
      - name: enable
        value: 1
      - name: transpose
        value: 0
      - name: Rotation_type
        value: 0
  - name: ImageCropper
    parameters:
      - name: Enable
        value: 0
      - name: X Offset
        value: 0
      - name: Y Offset
        value: 0
      - name: X Reduction
        value: 0
      - name: Y Reduction
        value: 0
  - name: DeepDice
    parameters:
      - name: Enable
        value: 1
      - name: Debug contour
        value: 1
      - name: dice1
        value: 0
      - name: dice2
        value: 1
      - name: dice5
        value: 0
      - name: dice6
        value: 0
      - name: roulette
        value: 0
      - name: path
        value: 0
      - name: cashinred
        value: 0
      - name: cashingreend
        value: 0
      - name: slot_machine
        value: 0
      - name: dollar_sign
        value: 0