name: simple_roulette
filters:
  - name: Rotate
    parameters:
      - name: enable
        value: 0
      - name: transpose
        value: 0
      - name: Rotation_type
        value: 3
  - name: ImageCropper
    parameters:
      - name: Enable
        value: 1
      - name: X Offset
        value: 281
      - name: Y Offset
        value: 0
      - name: X Reduction
        value: 245
      - name: Y Reduction
        value: 17
  - name: ContrastBrightness
    parameters:
      - name: enable
        value: 1
      - name: Contrast
        value: 3.000000
      - name: Brightness
        value: -135.000000
  - name: SubtractAllPlanes
    parameters:
      - name: enable
        value: 1
      - name: Plane_1
        value: 3
      - name: Plane_2
        value: 7
      - name: Plane_3
        value: 7
      - name: Invert_plane_1
        value: 0
      - name: Invert_plane_2
        value: 0
      - name: Invert_plane_3
        value: 0
      - name: Weight_Plane_1
        value: 2.000000
      - name: Weight_Plane_2
        value: 0.000000
      - name: Weight_Plane_3
        value: 2.000000
  - name: Blurr
    parameters:
      - name: Enable
        value: 1
      - name: Type
        value: 3
      - name: Kernel_size
        value: 8
  - name: SubtractAllPlanes
    parameters:
      - name: enable
        value: 1
      - name: Plane_1
        value: 7
      - name: Plane_2
        value: 7
      - name: Plane_3
        value: 7
      - name: Invert_plane_1
        value: 0
      - name: Invert_plane_2
        value: 0
      - name: Invert_plane_3
        value: 0
      - name: Weight_Plane_1
        value: 0.000000
      - name: Weight_Plane_2
        value: 10.000000
      - name: Weight_Plane_3
        value: 10.000000
  - name: Sobel
    parameters:
      - name: Enable
        value: 0
      - name: Convert_to_uchar
        value: 1
      - name: use_pixel_intensity_correction
        value: 0
      - name: Delta
        value: 0.000000
      - name: Scale
        value: 54.000000
      - name: pixel_correction_power
        value: 3.000000
      - name: Size
        value: 1
  - name: StatsThreshold
    parameters:
      - name: Enable
        value: 0
      - name: Min_thresh
        value: 0
      - name: Mean_multiplier
        value: -10.000000
      - name: Standard_deviation_multiplier
        value: 1.000000
  - name: Erode
    parameters:
      - name: Enable
        value: 1
      - name: Square_kernel
        value: 1
      - name: Kernel_type
        value: 0
      - name: Width
        value: 4
      - name: Height
        value: 3
      - name: Iteration
        value: 1
  - name: Blurr
    parameters:
      - name: Enable
        value: 1
      - name: Type
        value: 0
      - name: Kernel_size
        value: 7
  - name: Threshold
    parameters:
      - name: Enable
        value: 1
      - name: Threshold_type
        value: 0
      - name: Max_value
        value: 40
  - name: Erode
    parameters:
      - name: Enable
        value: 1
      - name: Square_kernel
        value: 1
      - name: Kernel_type
        value: 0
      - name: Width
        value: 9
      - name: Height
        value: 1
      - name: Iteration
        value: 1
  - name: PipeDetector
    parameters:
      - name: Enable
        value: 1
      - name: Debug_contour
        value: 1
      - name: Look_for_Rectangle
        value: 0
      - name: Min_area
        value: 200.000000