name: simple_align_test
filters:
  - name: SubtractAllPlanes
    parameters:
      - name: enable
        value: 1
      - name: Plane_1
        value: 5
      - name: Plane_2
        value: 4
      - name: Plane_3
        value: 0
      - name: Invert_plane_1
        value: 0
      - name: Invert_plane_2
        value: 0
      - name: Invert_plane_3
        value: 0
      - name: Weight_Plane_1
        value: 1.000000
      - name: Weight_Plane_2
        value: 1.000000
      - name: Weight_Plane_3
        value: 1.000000
  - name: Threshold
    parameters:
      - name: Enable
        value: 1
      - name: Threshold_type
        value: 0
      - name: Max_value
        value: 235
  - name: Dilate
    parameters:
      - name: Enable
        value: 1
      - name: Square_kernel
        value: 1
      - name: Kernel_type
        value: 0
      - name: Width
        value: 2
      - name: Height
        value: 2
      - name: Iteration
        value: 4
  - name: Erode
    parameters:
      - name: Enable
        value: 1
      - name: Square_kernel
        value: 1
      - name: Kernel_type
        value: 0
      - name: Width
        value: 10
      - name: Height
        value: 10
      - name: Iteration
        value: 1
  - name: Blurr
    parameters:
      - name: Enable
        value: 1
      - name: Type
        value: 2
      - name: Kernel_size
        value: 8
  - name: Dilate
    parameters:
      - name: Enable
        value: 1
      - name: Square_kernel
        value: 1
      - name: Kernel_type
        value: 0
      - name: Width
        value: 7
      - name: Height
        value: 7
      - name: Iteration
        value: 1
  - name: Blurr
    parameters:
      - name: Enable
        value: 1
      - name: Type
        value: 3
      - name: Kernel_size
        value: 17
  - name: Threshold
    parameters:
      - name: Enable
        value: 1
      - name: Threshold_type
        value: 0
      - name: Max_value
        value: 100
  - name: VampireTorpidoesDetectorClose
    parameters:
      - name: Enable
        value: 1
      - name: Debug_contour
        value: 1
      - name: Look_for_Ellipse
        value: 0
      - name: Look_for_Heart
        value: 0
      - name: Min_area
        value: 500.000000
      - name: Max_area
        value: 100000.000000