name: simple_gate
filters:
  - name: ImageCropper
    parameters:
      - name: Enable
        value: 0
      - name: X Offset
        value: 0
      - name: Y Offset
        value: 0
      - name: X Reduction
        value: 0
      - name: Y Reduction
        value: 0
  - name: Rotate
    parameters:
      - name: enable
        value: 0
      - name: transpose
        value: 0
      - name: Rotation_type
        value: 0
  - name: ContrastBrightness
    parameters:
      - name: enable
        value: 1
      - name: Contrast
        value: 6.000000
      - name: Brightness
        value: 80.000000
  - name: WhiteNoiseTakedown
    parameters:
      - name: Enable
        value: 1
      - name: LowB
        value: 255
      - name: HighB
        value: 255
      - name: LowG
        value: 0
      - name: HighG
        value: 0
      - name: LowR
        value: 126
      - name: HighR
        value: 205
      - name: Channel_view
        value: 0
  - name: SubtractAllPlanes
    parameters:
      - name: enable
        value: 0
      - name: Plane_1
        value: 5
      - name: Plane_2
        value: 3
      - name: Plane_3
        value: 7
      - name: Invert_plane_1
        value: 0
      - name: Invert_plane_2
        value: 0
      - name: Invert_plane_3
        value: 0
      - name: Weight_Plane_1
        value: 10.000000
      - name: Weight_Plane_2
        value: 7.000000
      - name: Weight_Plane_3
        value: 1.000000
  - name: Threshold
    parameters:
      - name: Enable
        value: 1
      - name: Threshold_type
        value: 4
      - name: Max_value
        value: 145
  - name: Blurr
    parameters:
      - name: Enable
        value: 0
      - name: Type
        value: 3
      - name: Kernel_size
        value: 9
  - name: ObjectFinder
    parameters:
      - name: Enable
        value: 1
      - name: Debug_contour
        value: 1
      - name: Use_convex_hull
        value: 0
      - name: Offset Y for fence
        value: 0
      - name: Offset Y for fence fraction
        value: 0.300000
      - name: 0. Check max y
        value: 0
      - name: 6. check_center_is_black_
        value: 0
      - name: 6. check_center_is_white_
        value: 1
      - name: 0. Maximum y coordinate
        value: 0.000000
      - name: "1. Min_area : red"
        value: 200.000000
      - name: "2. disable_ratio_check : blue"
        value: 0
      - name: 2. Ratio_target
        value: 0.500000
      - name: 2. Diff_from_ratio_target
        value: 0.100000
      - name: "3. Min_percent_filled : yellow"
        value: 50.000000
      - name: "3.1 Max_percent_filled : yellow"
        value: 100.000000
      - name: "4.1 Look_for_Rectangle : green"
        value: 1
      - name: "4.2 disable_angle_check : green"
        value: 1
      - name: 4.2 angle_target
        value: 0.000000
      - name: 4.2 Diff_from_angle_target
        value: 30.000000
      - name: 5. Eliminate_same_x
        value: 0
      - name: 5. Min_x_difference
        value: 50.000000
      - name: 6. check_min_size_
        value: 0
      - name: 6.1 min_height
        value: 50.000000
      - name: 6.2 min_width
        value: 50.000000
      - name: Vote_most_centered
        value: 0
      - name: Vote_most_upright
        value: 0
      - name: Vote_less_diff_from_target_ratio
        value: 0
      - name: Vote_length
        value: 0
      - name: Vote_higher
        value: 1
      - name: Vote most horizontal
        value: 0
      - name: ID
        value: buoy
      - name: spec1
        value: red
      - name: spec2
        value: blue
      - name: Contour_retreval
        value: 4
  - name: Blurr
    parameters:
      - name: Enable
        value: 0
      - name: Type
        value: 3
      - name: Kernel_size
        value: 35
  - name: SquareDetection
    parameters:
      - name: Enable
        value: 0
      - name: N
        value: 100
      - name: threshold
        value: 100