name: simple_torpille
filters:
  - name: Rotate
    parameters:
      - name: enable
        value: 1
      - name: transpose
        value: 0
      - name: Rotation_type
        value: 0
  - name: ImageCropper
    parameters:
      - name: Enable
        value: 0
      - name: X Offset
        value: 0
      - name: Y Offset
        value: 0
      - name: X Reduction
        value: 0
      - name: Y Reduction
        value: 0
  - name: ContrastBrightness
    parameters:
      - name: enable
        value: 1
      - name: Contrast
        value: 4.000000
      - name: Brightness
        value: 43.000000
  - name: SubtractAllPlanes
    parameters:
      - name: enable
        value: 1
      - name: Plane_1
        value: 3
      - name: Plane_2
        value: 4
      - name: Plane_3
        value: 2
      - name: Invert_plane_1
        value: 0
      - name: Invert_plane_2
        value: 0
      - name: Invert_plane_3
        value: 0
      - name: Weight_Plane_1
        value: 1.000000
      - name: Weight_Plane_2
        value: 1.000000
      - name: Weight_Plane_3
        value: 1.000000
  - name: Blurr
    parameters:
      - name: Enable
        value: 1
      - name: Type
        value: 2
      - name: Kernel_size
        value: 33
  - name: Threshold
    parameters:
      - name: Enable
        value: 1
      - name: Threshold_type
        value: 5
      - name: Max_value
        value: 148
  - name: PipeDetector
    parameters:
      - name: Enable
        value: 1
      - name: Debug_contour
        value: 1
      - name: Look_for_Rectangle
        value: 0
      - name: Min_area
        value: 217.000000