name: simple_align_test
filters:
  - name: SubtractAllPlanesFilter
    parameters:
      - name: Enable
        value: 1
      - name: Plane 1
        value: 5
      - name: Plane 2
        value: 4
      - name: Plane 3
        value: 0
      - name: Invert plane 1
        value: 0
      - name: Invert plane 2
        value: 0
      - name: Invert plane 3
        value: 0
      - name: Weight plane 1
        value: 1.000000
      - name: Weight plane 2
        value: 1.000000
      - name: Weight plane 3
        value: 1.000000
  - name: ThresholdFilter
    parameters:
      - name: Enable
        value: 1
      - name: Threshold type
        value: 0
      - name: Maximum value
        value: 150
  - name: DilateFilter
    parameters:
      - name: Enable
        value: 1
      - name: Square kernel
        value: 1
      - name: Kernel type
        value: 0
      - name: Width
        value: 2
      - name: Height
        value: 2
      - name: Iteration
        value: 4
  - name: ErodeFilter
    parameters:
      - name: Enable
        value: 1
      - name: Square kernel
        value: 1
      - name: Kernel type
        value: 0
      - name: Width
        value: 10
      - name: Height
        value: 10
      - name: Iteration
        value: 1
  - name: BlurFilter
    parameters:
      - name: Enable
        value: 1
      - name: Type
        value: 2
      - name: Kernel size
        value: 8
  - name: DilateFilter
    parameters:
      - name: Enable
        value: 0
      - name: Square kernel
        value: 1
      - name: Kernel type
        value: 0
      - name: Width
        value: 7
      - name: Height
        value: 7
      - name: Iteration
        value: 4
  - name: BlurFilter
    parameters:
      - name: Enable
        value: 0
      - name: Type
        value: 3
      - name: Kernel size
        value: 17
  - name: ThresholdFilter
    parameters:
      - name: Enable
        value: 1
      - name: Threshold type
        value: 0
      - name: Maximum value
        value: 100
  - name: VampireTorpedoesCloseDetector
    parameters:
      - name: Enable
        value: 1
      - name: Debug contour
        value: 1
      - name: Look for ellipse
        value: 0
      - name: Look_for_Heart
        value: 0
      - name: Minimum area
        value: 500.000000
      - name: Maximum area
        value: 100000.000000