name: Factory Generator

on:
  push:
    branches:
      - "feature/**"
      - "develop"
      - "master"
      - "main"

jobs:
  factory-generator:
    name: "Factory Generator"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/factory_generator
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest pytest-cov pytest-html

      - name: Run tests
        run: |
          cd app/tests
          PYTHONPATH=../../app pytest --cov-report html:tests_coverage --html=tests_run/index.html

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Factory Generator Tests Results
          path: |
            src/factory_generator/app/tests/tests_run
            src/factory_generator/app/tests/tests_coverage
        if: always()