name: SonarCloud

on:
  push:

jobs:
  sonarcloud:
    name: "SonarCloud"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set environment variables
        id: vars
        run: |
          echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"

      - name: Build, Analyze and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.sonarcloud
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          tags: ghcr.io/sonia-auv/proc_image_processing/sonarcloud:cache
          build-args: |
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN=${{secrets.SONAR_TOKEN}}
            BRANCH=${{ steps.vars.outputs.branch }}

      - # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache