name: SonarCloud

on:
  push:

jobs:
  sonarcloud:
    name: "SonarCloud"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set environment variables
        id: vars
        run: |
          echo "::set-output name=branch::${GITHUB_REF##*/}"

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.sonarcloud
          push: true
          tags: ghcr.io/sonia-auv/proc_image_processing/sonarcloud:cache
          cache-from: type=registry,ref=ghcr.io/sonia-auv/proc_image_processing/sonarcloud:cache
          cache-to: type=inline
          build-args: |
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN=${{secrets.SONAR_TOKEN}}
            BRANCH=${{ steps.vars.outputs.branch }}